In [13]:
import pandas as pd
import numpy as np
import pygal

In [5]:
iris = pd.read_csv('Iris.csv')
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [7]:
iris.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [9]:
pd.value_counts(iris['Species'], sort = True).sort_index()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: Species, dtype: int64

In [10]:
iris.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [11]:
iris.groupby('Species').mean()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm
Species,,,,,
Iris-setosa,25.5,5.006,3.418,1.464,0.244
Iris-versicolor,75.5,5.936,2.770,4.260,1.326
Iris-virginica,125.5,6.588,2.974,5.552,2.026

In [66]:
irissetosa = iris['Species'].map(lambda x: x.startswith('Iris-setosa'))
irisversicolor = iris['Species'].map(lambda x: x.startswith('Iris-versicolor'))
irisvirginica = iris['Species'].map(lambda x: x.startswith('Iris-virginica'))
listA = iris[irissetosa].loc[:, lambda df: ['SepalLengthCm']]
listB = iris[irisversicolor].loc[:, lambda df: ['SepalLengthCm']]
listC = iris[irisvirginica].loc[:, lambda df: ['SepalLengthCm']]
listD = iris[irissetosa].loc[:, lambda df: ['SepalWidthCm']]
listE = iris[irisversicolor].loc[:, lambda df: ['SepalWidthCm']]
listF = iris[irisvirginica].loc[:, lambda df: ['SepalWidthCm']]
listA

    SepalLengthCm
0             5.1
1             4.9
2             4.7
3             4.6
4             5.0
5             5.4
6             4.6
7             5.0
8             4.4
9             4.9
10            5.4
11            4.8
12            4.8
13            4.3
14            5.8
15            5.7
16            5.4
17            5.1
18            5.7
19            5.1
20            5.4
21            5.1
22            4.6
23            5.1
24            4.8
25            5.0
26            5.0
27            5.2
28            5.2
29            4.7
30            4.8
31            5.4
32            5.2
33            5.5
34            4.9
35            5.0
36            5.5
37            4.9
38            4.4
39            5.1
40            5.0
41            4.5
42            4.4
43            5.0
44            5.1
45            4.8
46            5.1
47            4.6
48            5.3
49            5.0

In [71]:
dot_chart = pygal.Dot(x_label_rotation=30)
dot_chart.title = 'V8 benchmark results'
dot_chart.x_labels = [map(float, range(4, 6))]
dot_chart.add('Iris-setosa', listA)
dot_chart.render()

TypeError: bad operand type for abs(): 'str'